import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Transactional } from 'typeorm-transactional';
import { TagOrmEntity, TagRepositoryImpl, Tag } from '@my-workspace/tags';
import { CreateTagDto, UpdateTagDto } from '@my-workspace/tags';

@Injectable()
export class TagsService {
  constructor(
    @InjectRepository(TagOrmEntity)
    private readonly ormRepository: Repository<TagOrmEntity>,
    private readonly tagRepository: TagRepositoryImpl
  ) {}

  @Transactional()
  async create(createTagDto: CreateTagDto) {
    // Create domain entity (slug will be generated by database trigger)
    const tag = Tag.create({
      name: createTagDto.name,
      description: createTagDto.description,
      color: createTagDto.color,
    });

    // Save using repository (automatically within transaction)
    // Database triggers will generate slug and code
    const saved = await this.tagRepository.save(tag);

    // Return ORM entity for admin panel
    return await this.ormRepository.findOne({
      where: { id: saved.id },
    });
  }

  async findAll() {
    return await this.ormRepository.find({
      order: { createdAt: 'DESC' },
    });
  }

  async findOne(tagId: number) {
    const tag = await this.tagRepository.findById(tagId);

    if (!tag) {
      throw new NotFoundException(`Tag with ID ${tagId} not found`);
    }

    // Return ORM entity for admin panel
    return await this.ormRepository.findOne({
      where: { id: tagId },
    });
  }

  @Transactional()
  async update(tagId: number, updateTagDto: UpdateTagDto) {
    const tag = await this.tagRepository.findById(tagId);

    if (!tag) {
      throw new NotFoundException(`Tag with ID ${tagId} not found`);
    }

    // Update domain entity
    if (updateTagDto.name && updateTagDto.name !== tag.name) {
      tag.updateName(updateTagDto.name);
      // Database trigger will regenerate slug on update
    }

    if (updateTagDto.description !== undefined) {
      tag.updateDescription(updateTagDto.description);
    }

    if (updateTagDto.color !== undefined) {
      tag.updateColor(updateTagDto.color);
    }

    // Save using repository (automatically within transaction)
    await this.tagRepository.update(tag);

    // Return ORM entity for admin panel
    return await this.ormRepository.findOne({
      where: { id: tagId },
    });
  }

  @Transactional()
  async remove(tagId: number) {
    // Check if tag exists
    const tag = await this.tagRepository.findById(tagId);

    if (!tag) {
      throw new NotFoundException(`Tag with ID ${tagId} not found`);
    }

    // Delete using repository (automatically within transaction)
    await this.tagRepository.delete(tagId);

    return { message: 'Tag deleted successfully' };
  }
}
